# Generated by Django 4.1.4 on 2022-12-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pagos_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='penalty_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='servicio',
            field=models.CharField(choices=[('NF', 'Netflix'), ('AP', 'Amazon Prime'), ('ST', 'Start Plus'), ('PM', 'Paramount Plus')], default='NF', max_length=2),
        ),
    ]
